apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sample-buildpacks-java-
spec:
  params:
    - name: gitRepo
      value: https://github.com/buildpacks/samples
    - name: AppImage
      value: image-registry.openshift-image-registry.svc:5000/demo/sample-java
    - name: sourceSubPath
      value: apps/java-maven
  pipelineRef:
    name: buildpacks
  workspaces:
    - name: source-ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: cache-ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi